name: Docs

on:
  push:
    branches: ["main"]


jobs:
  Build-Docs:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -U sphinx
        pip install sphinx_rtd_theme
    - name: Make the sphinx docs
      run: |
        make -C docs clean
        make -C docs html
    - name: Commit to gh-pages branch
      run: |
        git checkout -b gh-pages
        touch .nojekyll
        git add docs/build/html
        git commit -m "Update docs"
    - name: Push to gh-pages branch
      run: |
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./docs/build/html
